sources:
  - name: source
    database: dbt_tutorial_dev  
    schema: source  
    tables:
      - name: fact_sales
      - name: fact_returns
      - name: dim_customer
      - name: dim_store
      - name: dim_date
      - name: dim_product
      - name: items